repos:
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.3
    hooks:
      - id: pymarkdown
        name: PyMarkdown
        description: "PyMarkdown"
        files: ^README\.md$
        entry: pymarkdown
        args:
          - --config=clean.json
          - scan
