name: Main

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  scenario-tests:
    strategy:
      matrix:
        python: [3.8]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install PipEnv
        uses: dschep/install-pipenv-action@v1
        with:
          version: 2021.5.29
      - name: Sync With Repository
        run: pipenv sync
      - name: Execute Tests
        run: pipenv run pytest --cov-fail-under=90 --cov --cov-branch --cov-report xml:report/coverage.xml --cov-report html:report/coverage
  lint:
    strategy:
      matrix:
        python: [3.8]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install PipEnv
        uses: dschep/install-pipenv-action@v1
      - name: Sync With Repository
        run: pipenv sync
      - name: Execute Flake8
        run: pipenv run flake8 --exclude dist,build
      - name: Execute PyLint on Source
        run: pipenv run pylint --rcfile=setup.cfg ./pyscan
      - name: Execute PyLint on Tests
        run: pipenv run pylint --rcfile=setup.cfg ./test
